### PR TITLE
Add documentation for the requirement that LDAP user records must have "objectClass: user"

### PR DESCRIPTION
**Pull request by paulcwarren**
[#170116507](https://www.pivotaltracker.com/story/show/170116507)

cc @julian-hj @dennisdenuto @lisamcho

### CODE REVIEW

**Comment by cshollingsworth** [comment]
Hi, @paulcwarren -- does this change also need to be made in previous versions, or just 2.9?

**Comment by paulcwarren** [comment]
Hi @cshollingsworth it does but there should be separate PRs for each PAS version that we wanted to make the change to. 

The story above has all of the PRs listed.

HTH

**Comment by cshollingsworth** [comment]
@paulcwarren Not a problem! I can easily cherry-pick this to all the others, unless there are particular details that change from version to version.

**Comment by cshollingsworth** [comment]
@paulcwarren Got it. Will take a look. Thanks!

**Comment by cshollingsworth** [comment]
@paulcwarren All changes have been merged, and you should see them up on the docs site soon. Thank you!

**Comment by paulcwarren** [comment]
Thanks much

**Pull request closed without merging**
