### PR TITLE
UAA doc: clarify use of multiple URLs in LDAP Server URLs

### PR DESCRIPTION
**Pull request by peterhaochen47**
Please see commit message for details.

Please provide feedback on whether the new language is clear. Thanks!

And please backport this to all TAS versions.

### CODE REVIEW

**Comment by anita-flegg** [comment]
@fifthposition

**Comment by fifthposition** [comment]
@anita-flegg did you back-port this

**Comment by fifthposition** [comment]
@peterhaochen47 i think that the new text is clear enough. see the edited text here: https://github.com/pivotal-cf/docs-operating-pas/blob/4d243067f28e701b16d97eabc9f1247c0df0ccfd/auth-sso.html.md.erb#L117

**Comment by fifthposition** [comment]
backported to all supported TAS versions

**Pull request merged**
